[env:heltec_wifi_lora_32_V2]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0 
build_src_filter = +<heltec/> -<stm32/>

lib_ldf_mode = deep+
lib_deps =
    297
    https://github.com/ThingPulse/esp8266-oled-ssd1306.git
    jgromes/RadioLib @ ^6.6.0


[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
# Porta comum para o USB CDC do STM32 no Linux
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
build_src_filter = +<stm32/> -<heltec/>
lib_deps =
    jgromes/RadioLib @ ^6.6.0
    mikalhart/TinyGPSPlus